apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment2
  labels:
    app: add
    version: "v2"
  annotations:
      "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: add
      version: "v2"
  template:
    metadata:
      labels:
        app: add
        version: "v2"
    spec:
      containers:
      - name: add-ms
        image: smixi/add-ms
        ports:
        - containerPort: 5000
        env:
          - name: MS_EVAL
            value: "http://eval-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"