apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: eval
spec:
  host: eval-service
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v0
    labels:
      version: v0
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eval
spec:
  hosts:
  - eval-service
  http:
  - route:
    - destination:
        host: eval-service
        subset: v0
      weight: 100
    - destination:
        host: eval-service
        subset: v1
      weight: 0