apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: add
spec:
  host: add-service
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: add
spec:
  hosts:
  - add-service
  http:
  - route:
    - destination:
        host: add-service
        subset: v1
      weight: 10
    - destination:
        host: add-service
        subset: v2
      weight: 90