version: "3"
services:
  add:
    image: smixi/add-ms
    ports:
      - "4000:5000"
    environment:
      MS_EVAL: "http://eval:5000"
      TRACER_HOST: "jaeger"
    networks:
      - calculator-network
  sub:
    image: smixi/sub-ms
    ports:
      - "4001:5000"
    environment:
      MS_EVAL: "http://eval:5000"
      TRACER_HOST: "jaeger"
    networks:
      - calculator-network
  mult:
    image: smixi/mult-ms
    ports:
      - "4002:5000"
    environment:
      MS_EVAL: "http://eval:5000"
      TRACER_HOST: "jaeger"
    networks:
      - calculator-network
  div:
    image: smixi/div-ms
    ports:
      - "4003:5000"
    environment:
      MS_EVAL: "http://eval:5000"
      TRACER_HOST: "jaeger"
    networks:
      - calculator-network
  eval:
    image: smixi/eval-ms
    ports:
      - "4004:5000"
    environment:
      MS_ADD: "http://add:5000"
      MS_SUB: "http://sub:5000"
      MS_DIV: "http://div:5000"
      MS_MULT: "http://mult:5000"
      TRACER_HOST: "jaeger"
      REDIS_HOST: "redis"
    networks:
      - calculator-network
  parse:
    image: smixi/parse-ms
    ports:
      - "4005:5000"
    environment:
      MS_EVAL: "http://eval:5000"
      TRACER_HOST: "jaeger"
    networks:
      - calculator-network
      - out-network
    labels:
      kompose.service.type: LoadBalancer
      kompose.service.expose: "true"

  redis: 
    image: redis
    ports: 
      - "6379:6379"
    networks:
    - calculator-network
    command: "redis-server --protected-mode no --requirepass password"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831"
      - "16686:16686"
    networks:
      - calculator-network
networks:
  calculator-network:
  out-network:
